spring:
  profiles:
    active: dev, base-addi
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/app?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
custom:
  genFileDirPath: /Users/hongsikcho/Desktop/temp/app10/